# Generated by Django 4.0.3 on 2022-05-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='pics')),
                ('address', models.TextField()),
            ],
        ),
    ]
